### ISSUE TITLE
EconomyAPI Support - COMPLETED

### ISSUE THREAD

**Issue by shreyop200** [Vqnic/BloodyEnvoys#1]
This Plugin Looks Good And Stylish, but I Wish it Have EconomyAPI Support Also!

**Comment by Vqnic** [comment]
> This Plugin Looks Good And Stylish, but I Wish it Have EconomyAPI Support Also!

I'm not well-versed in the economy plugins most servers use, so I went with the one that seemed to be the most supported.

After brief research, I elected not to support EconomyAPI because it will no longer be receiving support, but if that's something people want I definitely can add it.

Additionally, thank you for the compliment. :)

**Comment by shreyop200** [comment]
> > This Plugin Looks Good And Stylish, but I Wish it Have EconomyAPI Support Also!
> 
> I'm not well-versed in the economy plugins most servers use, so I went with the one that seemed to be the most supported.
> 
> After brief research, I elected not to support EconomyAPI because it will no longer be receiving support, but if that's something people want I definitely can add it.
> 
> Additionally, thank you for the compliment. :)

I Appreciate Your Dedication Towards This Plugin, Will be Waiting For the New Update!

**Comment by Vqnic** [comment]
> > > This Plugin Looks Good And Stylish, but I Wish it Have EconomyAPI Support Also!
> > 
> > 
> > I'm not well-versed in the economy plugins most servers use, so I went with the one that seemed to be the most supported.
> > After brief research, I elected not to support EconomyAPI because it will no longer be receiving support, but if that's something people want I definitely can add it.
> > Additionally, thank you for the compliment. :)
> 
> I Appreciate Your Dedication Towards This Plugin, Will be Waiting For the New Update!

This has been added and should (hopefully) work. Make another issue if it acts up lmao.
